name = "guestbook"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MESSAGES"
id = "3fc418eb9e924e2bb288836aa1021e16"

[[r2_buckets]]
binding = "FILES"
bucket_name = "guestbook-files"
