name = "guestbook"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MESSAGES"
id = "3fc418eb9e924e2bb288836aa1021e16"

[vars]
# Backblaze B2 授权 (keyID:applicationKey 的 Base64 编码)
# 示例: echo -n "keyID:applicationKey" | base64
B2_AUTH = "_base64_encoded_keyID:applicationKey_"